[platformio]
default_envs = release
src_dir = ../..
include_dir = ../../include
boards_dir = boards
core_dir = ../../../../.pio-core-typec
build_dir = ../../../../.pio-build-typec-c071

[env]
platform = ststm32@19.7.1
platform_packages =
    framework-arduinoststm32@4.21200.0
    toolchain-gccarmnoneeabi@~1.120301.0
board = typec_tester_c071g8
framework = arduino
extra_scripts = pre:scripts/compiler_flags.py
build_src_filter =
    +<src/*.c>
    +<target/stm32c071/src/main.cpp>
build_flags =
    -I../../include
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -DPIO_FRAMEWORK_ARDUINO_SERIAL_DISABLED
lib_ldf_mode = deep+
monitor_speed = 115200
upload_protocol = stlink

[env:release]

[env:office_silent]
build_flags =
    ${env.build_flags}
    -DTYPEC_TESTER_OFFICE_SILENT=1
